import { Inter } from "next/font/google";
import "./globals.css";
import { i18n } from "@/i18n.config";
import Header from "./components/header";
import localFont from "@next/font/local";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const IRANSansX = localFont({
  src: [
    {
      path: "../../public/fonts/IRANSansXRegular.ttf",
      style: "normal",
      weight: "400",
    },
  ],
  variable: "--font-IRANSansX",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// return array of locale(en, fa)
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params }) {
  const dir = params.lang === "en" ? "ltr" : "rtl";
  const fontFamily =
    params.lang === "en" ? inter.className : IRANSansX.className;
  return (
    <html lang={params.lang} dir={dir}>
      <body className={fontFamily}>
        <Header lang={params.lang} />
        <main className="max-w-[80rem] px-4 mx-auto my-20 ">{children}</main>
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
